output   = "my_models"
wipe     = true
no-tests = true
add-enum-types = true

[psql]
  dbname  = "example"
  host    = "localhost"
  port    = 5432
  user    = "postgres"
  pass    = "password"
  sslmode = "disable"